FinalShopCart/FinalShopCart/Controllers/ShoppingController.cs
using FinalShopCart.Models;
using FinalShopCart.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FinalShopCart.Controllers
{
 
    public class ShoppingController : Controller
    {
        private EcartDb2Entities1 objECartDbEntities;
        private List<ShoppingCartModel> listOfShoppingCartModels;
        public ShoppingController()
        {
            objECartDbEntities = new EcartDb2Entities1();
            listOfShoppingCartModels = new List<ShoppingCartModel>();
        }
        // GET: Shopping
        public ActionResult Index()
        {
            IEnumerable<ShoppingViewModel> listOfShoppingViewModels = (from objItem in objECartDbEntities.Items
                                                                       join
                                                                           objCate in objECartDbEntities.Categories
                                                                           on objItem.CategoryId equals objCate.CategoryId
                                                                       select new ShoppingViewModel()
                                                                       {
                                                                           ImagePath = objItem.ImagePath,
                                                                           ItemName = objItem.ItemName,
                                                                           Description = objItem.Description,
                                                                           ItemPrice = objItem.ItemPrice,
                                                                           ItemId = objItem.ItemId,
                                                                           Category = objCate.CategoryName,
                                                                           ItemCode = objItem.ItemCode
                                                                       }

                ).ToList();
            return View(listOfShoppingViewModels);
        }

        [HttpPost]
        public JsonResult Index(string ItemId)
        {
            ShoppingCartModel objShoppingCartModel = new ShoppingCartModel();
            Item objItem = objECartDbEntities.Items.Single(model => model.ItemId.ToString() == ItemId);
            if (Session["CartCounter"] != null)
            {
                listOfShoppingCartModels = Session["CartItem"] as List<ShoppingCartModel>;
            }
           
            if (listOfShoppingCartModels.Any(model => model.ItemId == ItemId))
            {

                objShoppingCartModel = listOfShoppingCartModels.Single(model => model.ItemId == ItemId);

                objShoppingCartModel.Quantity = objShoppingCartModel.Quantity + 1;

                objShoppingCartModel.Total = objShoppingCartModel.Quantity * objShoppingCartModel.UnitPrice;
                objShoppingCartModel.SubTotal =  objShoppingCartModel.Total;
                objShoppingCartModel.Tax = objShoppingCartModel.SubTotal * 10/100;
                objShoppingCartModel.GrandTotal = objShoppingCartModel.SubTotal + objShoppingCartModel.Tax;

            }
            else
            {
                objShoppingCartModel.ItemId = ItemId;
                objShoppingCartModel.ImagePath = objItem.ImagePath;
                objShoppingCartModel.ItemName = objItem.ItemName;
                objShoppingCartModel.Quantity = 1;
                objShoppingCartModel.Total = objItem.ItemPrice;
                objShoppingCartModel.UnitPrice = objItem.ItemPrice;
                objShoppingCartModel.SubTotal = objItem.ItemPrice;
                objShoppingCartModel.GrandTotal = objItem.ItemPrice + objItem.ItemPrice * 10 / 100;
                objShoppingCartModel.Tax = objItem.ItemPrice * 10 / 100;


                listOfShoppingCartModels.Add(objShoppingCartModel);
            }

            Session["CartCounter"] = listOfShoppingCartModels.Count;
            Session["CartItem"] = listOfShoppingCartModels;
            return Json(new { Success = true, Counter = listOfShoppingCartModels.Count }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult ItemsCounter(string ItemId,int quantity)
        {
            ShoppingCartModel objShoppingCartModel = new ShoppingCartModel();
            Item objItem = objECartDbEntities.Items.Single(model => model.ItemId.ToString() == ItemId);
            if (Session["CartCounter"] != null)
            {
                listOfShoppingCartModels = Session["CartItem"] as List<ShoppingCartModel>;
            }
            if (listOfShoppingCartModels.Any(model => model.ItemId == ItemId))
            {
                objShoppingCartModel = listOfShoppingCartModels.Single(model => model.ItemId == ItemId);

                objShoppingCartModel.Quantity = quantity;

                objShoppingCartModel.Total = objShoppingCartModel.Quantity * objShoppingCartModel.UnitPrice;
                objShoppingCartModel.SubTotal = objShoppingCartModel.Total;
                objShoppingCartModel.Tax = objShoppingCartModel.SubTotal * 10 / 100;
                objShoppingCartModel.GrandTotal = objShoppingCartModel.SubTotal + objShoppingCartModel.Tax;
            }

            Session["CartCounter"] = listOfShoppingCartModels.Count;
            Session["CartItem"] = listOfShoppingCartModels;
            return Json(new { Success = true, Counter = listOfShoppingCartModels.Count }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ShoppingCart()
        {
            listOfShoppingCartModels = Session["CartItem"] as List<ShoppingCartModel>;
            return View(listOfShoppingCartModels);
        }

        [HttpPost]
        public ActionResult AddOrder()
        {
            int OrderId = 0;
            listOfShoppingCartModels = Session["CartItem"] as List<ShoppingCartModel>;
            Order orderObj = new Order()
            {
                OrderDate = DateTime.Now,
                OrderNumber = String.Format("{0:ddmmyyyyHHmmsss}", DateTime.Now)
            };
            objECartDbEntities.Orders.Add(orderObj);
            objECartDbEntities.SaveChanges();
            OrderId = orderObj.OrderId;

            foreach (var item in listOfShoppingCartModels)
            {
        
                OrderDetail objOrderDetail = new OrderDetail();
                objOrderDetail.Total = item.Total;
                objOrderDetail.ItemId = item.ItemId;
                objOrderDetail.OrderId = OrderId;
                objOrderDetail.Quantity = item.Quantity;
                objOrderDetail.UnitPrice = item.UnitPrice;
                objOrderDetail.SubTotal = item.SubTotal;
                objOrderDetail.Tax = item.Tax;
                objOrderDetail.GrandTotal = item.GrandTotal;
               
           
               

                objECartDbEntities.OrderDetails.Add(objOrderDetail);
                objECartDbEntities.SaveChanges();
            }

            Session["CartItem"] = null;
            Session["CartCounter"] = null;
            //return RedirectToAction("Index");
            return RedirectToAction("Index", "Customer");
        }

        public ActionResult Remove(string id)
        {

            listOfShoppingCartModels = Session["CartItem"] as List<ShoppingCartModel>;
            ShoppingCartModel c = listOfShoppingCartModels.Where(x => x.ItemId == id).SingleOrDefault();
            listOfShoppingCartModels.Remove(c);

            decimal h = 0;
            foreach (var item in listOfShoppingCartModels)
            {
                h += item.Total;

            }
            TempData["total"] = h;
            TempData.Keep();
            return RedirectToAction("ShoppingCart");

        }

        //public ActionResult next()
        //{
            
        //    if(listOfShoppingCartModels.Count > 0)
        //    {
        //        return View("Index","Customer");
        //    }
        //    else


        //    return View("Index");
        //}

        //public ActionResult next()
        //{
           
        //        if (true)
        //        return RedirectToAction("Index");

        //    else

        //    return RedirectToAction("Index", "Home");
   
        
        
        //}
        public ActionResult next()
        {
            if(Session["cartCount"]==null)
            {
                return RedirectToAction("_shoppingCart");

            }
            else
            {
                return RedirectToAction("Index", "customer");
            }
        }

        //public ActionResult UpdateCart(FormCollection frc)
        //{
        //    string[] quantities = frc.GetValues("quantity");
        //    List<ShoppingCartModel> lsCart = (List<ShoppingCartModel>)Session["CartItem"];
        //    for (int i = 0; i < lsCart.Count; i++)
        //    {
        //        lsCart[i].Quantity = Convert.ToInt32(quantities[i]);
        //    }
        //    Session["CartItem"] = lsCart;
        //    return View("ShoppingCart");
        //}
        public ActionResult UpdateCart()
        {
            //string[] quantities = frc.GetValues("quantity");
            //    List<ShoppingCartModel> lsCart = (List<ShoppingCartModel>)Session["CartItem"];
            //   for (int i = 0; i < lsCart.Count; i++)
            //   {
            //        lsCart[i].Quantity = Convert.ToInt32(quantities[i]);
            //    }
            //   Session["CartItem"] = lsCart;
            //  //return View("ShoppingCart");
            return RedirectToAction("ShoppingCart");
        }
    }








}

FinalShopCart/FinalShopCart/Views/Shopping/Index.cshtml
@model IEnumerable<FinalShopCart.ViewModel.ShoppingViewModel>
@{
    ViewBag.Title = "Index"; 
    }

<script type="text/javascript">function AddToCart(item) {
        var itemId = $(item).attr("itemid");
        var formData = new FormData();
        formData.append("ItemId", itemId);

        $.ajax({
            async: true,
            type: 'POST',
            contentType: false,
            processData: false,
            data: formData,
            url: '/Shopping/Index',
            success: function(data) {
                if (data.Success) {
                    $("#cartItem").text("Cart(" + data.Counter + ")");
                }
            },
            error: function() {
                alert("There is some problem.");
            }
        });
    }</script>
<div class="container">
    <h2 class="text-center">Product List</h2>
    @foreach (var item in Model)
    {
<div class="col-md-4" style="border: 2px solid black">
    <div style="text-align: center; border-bottom: 2px solid maroon">
        <h3>@item.ItemName</h3>
    </div>
    <div>
        <div class="col-md-8">
            <img src="@Url.Content(@item.ImagePath)" width="150px" height="150px" />
        </div>
        <div class="col-md-4" style="text-align: left">
            <b>@item.Description</b>
        </div>
    </div>

    <div class="col-md-8" style="font-size: 18px; border-top: 2px solid maroon; padding: 2px">
        <b>@item.ItemPrice.ToString("#,##0.00 INR")</b>
    </div>
    <div class="col-md-4" style="text-align: right; margin-bottom: 10px; border-top: 2px solid maroon; padding: 2px">
        <input type="button" name="AddToCart" value="Add to Cart" class="btn btn-primary" itemid="@item.ItemId" id="btnAddToCart" onclick="AddToCart(this)" />
    </div>

</div>}
</div>

FinalShopCart/FinalShopCart/Views/Shopping/ShoppingCart.cshtml
@model IEnumerable<FinalShopCart.ViewModel.ShoppingCartModel>


@{
    ViewBag.Title = "ShoppingCart";

    decimal GrandTotalAmount = 0.00M;
    decimal SubTotalAmount = 0.00M;
    decimal TaxAmount = 0.00M;
}

<h2>Home Page</h2>

@{ if (Session["CartCounter"] != null)
    {

        using (Html.BeginForm("AddOrder", "Shopping", FormMethod.Post))
        {
    <table class="table-condensed" style="width: 100%">
        <tr>
            <th>Product Name</th>
            <th>Model </th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Total</th>
            <th>Action</th>

        </tr>
        @foreach (var item in Model)
        {
            TaxAmount = item.Tax;
            GrandTotalAmount = item.GrandTotal;
            SubTotalAmount += item.Total;
            TaxAmount = 10 * SubTotalAmount / 100;
            GrandTotalAmount = SubTotalAmount + TaxAmount;

            <tr>
                <td>
                    <img src="@Url.Content(item.ImagePath)" height="50px" width="50px" class="img-rounded" />
                </td>
                <td>
                    @item.ItemName
                </td>

                <td>
                    @*@item.Quantity*@
                    <input type="number" name="quantity" itemid="@item.ItemId" id="quantity" value="@item.Quantity.ToString("#,##0")" onchange = "AddToCart(this)" min="1" max="10" />
                    &nbsp;<span id="errmsg"></span>
                </td>

                <td>
                    @item.UnitPrice.ToString("#,##0.00")
                </td>
                <td>
                    @item.Total.ToString("#,##0.00")

                <td>
                    <a class="btn btn-danger btn-sm" href="@Url.Action("Remove", new{id=@item.ItemId})">&#10060;</a>

                    @*@Html.ActionLink("Delete", "Delete", "ShoppingCart", new { id = item.ItemId },
                    new { onclick = "return confirm ('Are you sure you want to delete this?');", @class = "delete-shopping" })*@
                </td>

            </tr>
        }
        <tr style="border-top: 2px solid maroon">
            <td colspan="5" style="text-align: right">
                <h3>Sub Total</h3>
            </td>
            <td style="text-align: right">
                <h3>@SubTotalAmount.ToString("#,##0.00")</h3>
            </td>
        </tr>

        <tr>
            <td colspan="5" style="text-align: right">
                <h3>Tax</h3>
            </td>
            <td style="text-align: right">
                <h3>@TaxAmount.ToString("#,##0.00")</h3>
            </td>
        </tr>


        <tr>
            <td colspan="5" style="text-align: right">
                <h3>Grand Total</h3>
            </td>
            <td style="text-align: right">
                <h3>@GrandTotalAmount.ToString("#,##0.00")</h3>
            </td>
        </tr>

        @*<tr style="text-align: right">
            <td colspan="5">
                <input type="submit" value="Save" name="Save" class="btn btn-primary" id="SaveOrder" />
            </td>
        </tr>*@

        <tr style="text-align: center">
            <td colspan="5">

                <input type="button" value="UpdateCart" class="btn btn-default" id="UpdateCart" onclick="location.href='@Url.Action("Updatecart", "Shopping")'" />

                @*@Html.ActionLink("Continue Shopping", "Index", "Shopping", new { @class = "btn btn-secondary" })*@

                <input type="button" value="continue shopping" class="btn btn-success" onclick="@("window.location.href='" + @Url.Action("Index", "Shopping") + "'");" />

                @*<input type="submit" value="Save" name="Save" class="btn btn-primary" id="SaveOrder" />*@

                <input type="button" value="Next" class="btn btn-primary" id="nextbutton" name="Check" onclick="onCheck()" />

                @*<input type="button" value="Next" class=" btn-success" id="check-out" onclick="@("window.location.href='" + @Url.Action("Index", "Customer") + "'");" />*@



            </td>
        </tr>
    </table>
        }

    }

    else
    {
        <h4> No items in your cart!!!</h4>
    }
}

<script type="text/javascript">
    $(document).ready(function () {
        var itemCount = $("tbody")[0].children.length;
        if (itemCount == 5) {
            $("#nextbutton").prop('disabled', true);
        }

        //called when key is pressed in textbox
        $("#quantity").keypress(function (e) {
            //if the letter is not a digit, we will display the error message and dont allow them to type anything
            if (e.which != 8 && e.which != 0 && (e.which < 48 || e.which > 57)) {
                //we will display error message
                $("#errmsg").html("Enter digits only!").show().fadeOut("slow");
                return false;
            }
        });
    });

    function onCheck() {
        sessionStorage.setItem("valid", "true");
        window.location.href = "/Customer";
    }

    function AddToCart(item) {
        var inputValue = item.value;
        var itemId = $(item).attr("itemid");
        var formData = new FormData();
        formData.append("ItemId", itemId);
        formData.append("quantity", inputValue);

        $.ajax({
            async: true,
            type: 'POST',
            contentType: false,
            processData: false,
            data: formData,
            url: '/Shopping/ItemsCounter',
            success: function (data) {
                console.log(data);
                if (data.Success) {
                    $("#cartItem").text("Cart(" + data.Counter + ")");
                }
            },
            error: function () {
                alert("There is some problem.");
            }
        });
    }
</script>